---
- hosts: kubernetes_master
  become: true
  tasks:
  - name: Get the token for joining the worker nodes
    ansible.builtin.shell: 
      cmd: kubeadm token create  --print-join-command
    become: yes
    become_user: user100
    register: kubernetes_join_command
  - name: Copy join command to local file.
    ansible.builtin.copy: 
      content: "{{ kubernetes_join_command.stdout_lines[0] }}"
      dest: "/tmp/kubernetes_join_command"
  - name: Copy join file to controller
    ansible.builtin.fetch:
      src: "/tmp/kubernetes_join_command"
      dest: "/tmp/kubernetes_join_command"
      flat: yes
  - name: Remove local join command file
    ansible.builtin.file:
      path: "/tmp/kubernetes_join_command"
      state: absent

- hosts: kubernetes_worker
  become: true
  tasks:
  - name: Copy join command from Ansiblehost to the worker nodes.
    ansible.builtin.copy:
      src: /tmp/kubernetes_join_command
      dest: /tmp/kubernetes_join_command
      mode: 0500
  - name: Join the Worker nodes to the cluster.
    ansible.builtin.command:
      cmd: sh /tmp/kubernetes_join_command