---
- hosts: kubernetes_master
  become: true
  handlers:
  - name: Sleep 45 seconds
    ansible.builtin.wait_for:
      timeout: 45
    listen: sleep 45 sec
    delegate_to: localhost
  tasks:
  - name: Generate 32 byte secret
    ansible.builtin.shell: head -c 32 /dev/urandom | base64
    register: secret_key
    changed_when: false
  - name: Copy kube encryption file
    ansible.builtin.copy:
      src: kube_encryption.yml
      dest: /etc/kubernetes/pki/enc-config.yaml
  - name: Replace text with secret word
    ansible.builtin.replace:
      path: /etc/kubernetes/pki/enc-config.yaml
      regexp: 'secret_key'
      replace: "{{ secret_key.stdout }}"
  - name: Add the encryption parameter to kube-apiserver config file
    ansible.builtin.lineinfile:
      path: /etc/kubernetes/manifests/kube-apiserver.yaml
      insertbefore: '    - --enable-admission-plugins=NodeRestriction'
      line: '    - --encryption-provider-config=/etc/kubernetes/pki/enc-config.yaml'
    notify: sleep 45 sec