---
- name: exit if distribution is not supported
  ansible.builtin.fail:
    msg: "Distribution {{ ansible_facts['distribution'] }} is not supported"
  when: ansible_facts['distribution'] not in kubernetesRole_supportedDebianDistros and ansible_facts['distribution'] not in kubernetesRole_supportedFedoraDistros
- name: set an optional environment with proxy vars
  ansible.builtin.set_fact:
    proxy_env:
      http_proxy: "{{ kubernetesRole_httpProxy }}"
      https_proxy: "{{ kubernetesRole_httpsProxy }}"
      no_proxy: "{{ kubernetesRole_noProxy }}"
  when: kubernetesRole_useProxy
- name: Allow firewall ports for kubernetes master Debian
  community.general.ufw:
    rule: allow
    proto: "{{ item.proto }}"
    port: "{{ item.port }}"
  loop: "{{ kubernetesRole_masterFirewall }}"
  when: "'kubernetes_master' in group_names and ansible_facts['distribution'] in kubernetesRole_supportedDebianDistros"
  notify: restart ufw
- name: Allow firewall ports for kubernetes workers Debian
  community.general.ufw:
    rule: allow
    proto: "{{ item.proto }}"
    port: "{{ item.port }}"
  loop: "{{ kubernetesRole_workerFirewall }}"
  when: "'kubernetes_worker' in group_names  and ansible_facts['distribution'] in kubernetesRole_supportedDebianDistros"
  notify: restart ufw
- name: 'Allow ufw DEFAULT_FORWARD_POLICY=ACCEPT'
  ufw:
    direction: routed
    default: allow
    route: yes
  when: "ansible_facts['distribution'] in kubernetesRole_supportedDebianDistros"
  notify: restart ufw
- name: Allow firewall ports for kubernetes master Fedora
  ansible.posix.firewalld:
    port: "{{ item.port }}/{{ item.proto }}"
    permanent: true
    state: enabled
  when: "'kubernetes_master' in group_names  and ansible_facts['distribution'] in kubernetesRole_supportedFedoraDistros"
  loop: "{{ kubernetesRole_masterFirewall }}"
  notify: restart firewalld
- name: Allow firewall ports for kubernetes worker Fedora
  ansible.posix.firewalld:
    port: "{{ item.port | replace(':','-') }}/{{ item.proto }}"
    permanent: true
    state: enabled
  when: "'kubernetes_worker' in group_names  and ansible_facts['distribution'] in kubernetesRole_supportedFedoraDistros"
  loop: "{{ kubernetesRole_workerFirewall }}"
  notify: restart firewalld
- name: enable masquarade for firewalld
  ansible.posix.firewalld:
    masquerade: true
    state: enabled
    permanent: true
  when: "ansible_facts['distribution'] in kubernetesRole_supportedFedoraDistros"
  notify: restart firewalld
- name: disable swap in running instance
  ansible.builtin.command:
    cmd: swapoff -a
  changed_when: false
- name: disable swap in the fstab file
  ansible.builtin.replace:
    path: /etc/fstab
    regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
    replace: '# \1'
- name: create a empty file for containerd module.
  ansible.builtin.copy:
    content: ""
    dest: /etc/modules-load.d/containerd.conf
    force: no
- name: configure module for containerd.
  ansible.builtin.blockinfile:
    path: /etc/modules-load.d/containerd.conf
    block: |
          overlay
          br_netfilter
- name: Add modules
  community.general.modprobe:
    name: "{{ item  }}"
    state: present
  loop: "{{ kubernetesRole_containerdModules }}"
- name: create a empty file for kubernetes sysctl params.
  ansible.builtin.copy:
    content: ""
    dest: /etc/sysctl.d/99-kubernetes-cri.conf
    force: no
- name: Configure sysctl params for Kubernetes.
  ansible.posix.sysctl:
    name: "{{ item  }}"
    value: '1'
    sysctl_set: true
    state: present
    reload: true
    sysctl_file: '/etc/sysctl.d/99-kubernetes-cri.conf'
  loop: "{{ kubernetesRole_sysctlParams }}"
- name: Installing Prerequisites for Kubernetes Debian
  ansible.builtin.apt:
    name: "{{ item  }}"
    state: present
  loop: "{{ kubernetesRole_prerequisites }}"
  when: "ansible_facts['distribution'] in kubernetesRole_supportedDebianDistros"
- name: Add docker repo to Fedora package manager
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docer-ce.repo
  environment: "{{ proxy_env | default(omit) }}"
  when: "ansible_facts['distribution'] in kubernetesRole_supportedFedoraDistros"
- name: Add Docker GPG apt Key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  environment: "{{ proxy_env | default(omit) }}"
  when: "ansible_facts['distribution'] in kubernetesRole_supportedDebianDistros"
- name: Add docker repo to Debian package manager
  ansible.builtin.apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu focal stable
    state: present
  when: "ansible_facts['distribution'] in kubernetesRole_supportedDebianDistros"
- name: Install containerd apt
  ansible.builtin.apt:
    name: containerd.io
    state: present
    update_cache: yes
  when: "ansible_facts['distribution'] in kubernetesRole_supportedDebianDistros"
- name: Install containerd yum
  ansible.builtin.yum:
    name: containerd.io
    state: present
    update_cache: yes
  when: "ansible_facts['distribution'] in kubernetesRole_supportedFedoraDistros"
- name: Start and enable containerd
  ansible.builtin.service:
    name: containerd
    state: started
    enabled: yes
- name: get containerd default settings
  ansible.builtin.command:
    cmd: containerd config default
  changed_when: false
  register: containerd_config
- name: set containerd config file
  ansible.builtin.copy:
    dest: "/etc/containerd/config.toml"
    content: "{{ containerd_config['stdout']  }}"
  notify: restart containerd
- name: Create containerd service directory
  ansible.builtin.file:
    path: /etc/systemd/system/containerd.service.d
    state: directory
- name: create a empty file for containerd service proxy
  ansible.builtin.copy:
    content: ""
    dest: /etc/systemd/system/containerd.service.d/http-proxy.conf
    force: no
  when: kubernetesRole_useProxy
- name: configure proxy for containerd
  ansible.builtin.blockinfile:
    path: /etc/systemd/system/containerd.service.d/http-proxy.conf
    block: |
          [Service]
          Environment="HTTP_PROXY={{ kubernetesRole_httpProxy }}"
          Environment="HTTPS_PROXY={{ kubernetesRole_httpsProxy }}"
          Environment="NO_PROXY=kubernetesRole_noProxy"
  notify: restart containerd
  when: kubernetesRole_useProxy
- name: Put SELinux in permissive mode, logging actions that would be blocked.
  ansible.posix.selinux:
    policy: targeted
    state: permissive
  when: "ansible_facts['distribution'] in kubernetesRole_supportedFedoraDistros"
- name: Add Google official GPG key
  ansible.builtin.apt_key:
    url: https://pkgs.k8s.io/core:/stable:/v1.28/deb/Release.key
    state: present
  environment: "{{ proxy_env | default(omit) }}"
  when: "ansible_facts['distribution'] in kubernetesRole_supportedDebianDistros"
- name: Add Kubernetes Repository apt
  ansible.builtin.apt_repository:
    repo: deb https://pkgs.k8s.io/core:/stable:/v1.28/deb/ /
    state: present
    filename: kubernetes
  when: "ansible_facts['distribution'] in kubernetesRole_supportedDebianDistros"
- name: Installing Kubernetes Cluster Packages apt.
  ansible.builtin.apt:
    name: "{{ item  }}={{ kubernetesRole_packagesVersionDebian }}"
    state: present
    update_cache: yes
  loop: "{{ kubernetesRole_kubernetesPackages }}"
  when: "ansible_facts['distribution'] in kubernetesRole_supportedDebianDistros"
- name: Hold kubernetes packages apt
  ansible.builtin.dpkg_selections:
    name: "{{ item  }}"
    selection: hold
  loop: "{{ kubernetesRole_kubernetesPackages }}"
  when: "ansible_facts['distribution'] in kubernetesRole_supportedDebianDistros"
- name: Copy Kubernetes repo file for yum
  ansible.builtin.template:
    src: kubernetes-yum.j2
    dest: /etc/yum.repos.d/kubernetes.repo
  when: "ansible_facts['distribution'] in kubernetesRole_supportedFedoraDistros"
- name: Installing Kubernetes Cluster Packages yum.
  ansible.builtin.yum:
    name: "{{ item  }}-{{ kubernetesRole_packagesVersionFedora }}"
    state: present
    update_cache: yes
    disable_excludes: kubernetes
  loop: "{{ kubernetesRole_kubernetesPackages }}"
  when: "ansible_facts['distribution'] in kubernetesRole_supportedFedoraDistros"
- name: configure proxy for kubelet
  ansible.builtin.blockinfile:
    path: /usr/lib/systemd/system/kubelet.service.d/10-kubeadm.conf
    block: |
          Environment="HTTP_PROXY={{ kubernetesRole_httpProxy }}"
          Environment="HTTPS_PROXY={{ kubernetesRole_httpsProxy }}"
          Environment="NO_PROXY={{ kubernetesRole_noProxy }}"
  notify: restart kubelet
  when: kubernetesRole_useProxy