---
- hosts: kubernetes_master
  become: true
  handlers:
  - name: Sleep 40 seconds
    ansible.builtin.wait_for:
      timeout: 40
    listen: sleep 40 sec
    delegate_to: localhost
  tasks:
  - name: Generate 32 byte secret
    shell: head -c 32 /dev/urandom | base64
    register: secret_key
    changed_when: false
  - name: Replace text with secret word
    replace:
      path: /etc/kubernetes/pki/enc-config.yaml
      regexp: 'secret_key'
      replace: "{{ secret_key.stdout }}"
  - name: Add the encryption parameter to kube-apiserver config file
    lineinfile:
      path: /etc/kubernetes/manifests/kube-apiserver.yaml
      insertbefore: '    - --enable-admission-plugins=NodeRestriction'
      line: '    - --encryption-provider-config=/etc/kubernetes/pki/enc-config.yaml'
    notify: sleep 40 sec