---
- name: Restart containerd
  ansible.builtin.systemd:
    state: restarted
    name: containerd
    daemon_reload: true
  listen: restart containerd
- name: Restart ufw
  ansible.builtin.systemd:
    state: restarted
    name: ufw
    daemon_reload: true
  listen: restart ufw
- name: Restart kubelet
  ansible.builtin.systemd:
    state: restarted
    name: kubelet
    daemon_reload: true
    enabled: yes
  listen: restart kubelet
- name: Restart firewalld
  ansible.builtin.systemd:
    state: restarted
    name: firewalld
    daemon_reload: true
  listen: restart firewalld