apiVersion: v1
kind: ServiceAccount
metadata:
  name: goldilocks-controller
  namespace: goldilocks
  labels:
    app: goldilocks
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: goldilocks-controller
  namespace: goldilocks
  labels:
    app: goldilocks
rules:
  - apiGroups:
      - 'apps'
    resources:
      - '*'
    verbs:
      - 'get'
      - 'list'
      - 'watch'
  - apiGroups:
      - ''
    resources:
      - 'namespaces'
      - 'pods'
    verbs:
      - 'get'
      - 'list'
      - 'watch'
  - apiGroups:
      - 'autoscaling.k8s.io'
    resources:
      - 'verticalpodautoscalers'
    verbs:
      - 'get'
      - 'list'
      - 'create'
      - 'delete'
      - 'update'
  - apiGroups:
      - 'argoproj.io'
    resources:
      - 'rollouts'
    verbs:
      - 'get'
      - 'list'
      - 'watch'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: goldilocks-controller
  namespace: goldilocks
  labels:
    app: goldilocks
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: goldilocks-controller
subjects:
  - kind: ServiceAccount
    name: goldilocks-controller
    namespace: goldilocks
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: goldilocks-controller
  namespace: goldilocks
  labels:
    app.kubernetes.io/name: goldilocks
    app.kubernetes.io/component: controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: goldilocks
      app.kubernetes.io/component: controller
  template:
    metadata:
      labels:
        app.kubernetes.io/name: goldilocks
        app.kubernetes.io/component: controller
    spec:
      serviceAccountName: goldilocks-controller
      containers:
        - name: goldilocks
          image: "us-docker.pkg.dev/fairwinds-ops/oss/goldilocks:master"
          imagePullPolicy: Always
          command:
            - /goldilocks
            - controller
          securityContext:
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 10324
            capabilities:
              drop:
                - ALL
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            requests:
              cpu: 25m
              memory: 32Mi
            limits:
              cpu: 25m
              memory: 32Mi